insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('adams', 'Adams', 'us', 'http://en.wikipedia.org/wiki/Adams_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('afm', 'AFM', 'de', 'http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ags', 'AGS', 'fr', 'http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('alfa', 'Alfa Romeo', 'ch', 'http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('alphatauri', 'AlphaTauri', 'it', 'http://en.wikipedia.org/wiki/Scuderia_AlphaTauri');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('alpine', 'Alpine F1 Team', 'fr', 'http://en.wikipedia.org/wiki/Alpine_F1_Team');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('alta', 'Alta', 'gb', 'http://en.wikipedia.org/wiki/Alta_auto_racing_team');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('amon', 'Amon', 'nz', 'http://en.wikipedia.org/wiki/Amon_(Formula_One_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('moda', 'Andrea Moda', 'it', 'http://en.wikipedia.org/wiki/Andrea_Moda_Formula');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('apollon', 'Apollon', 'ch', 'http://en.wikipedia.org/wiki/Apollon_(Formula_One)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('arrows', 'Arrows', 'gb', 'http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('arzani-volpini', 'Arzani-Volpini', 'it', 'http://en.wikipedia.org/wiki/Arzani-Volpini');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('butterworth', 'Aston Butterworth', 'gb', 'http://en.wikipedia.org/wiki/Aston_Butterworth');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('aston_martin', 'Aston Martin', 'gb', 'http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ats', 'ATS', 'it', 'http://en.wikipedia.org/wiki/ATS_(wheels)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('bar', 'BAR', 'gb', 'http://en.wikipedia.org/wiki/British_American_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('behra-porsche', 'Behra-Porsche', 'it', 'http://en.wikipedia.org/wiki/Behra-Porsche');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('bellasi', 'Bellasi', 'ch', 'http://en.wikipedia.org/wiki/Bellasi');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('benetton', 'Benetton', 'it', 'http://en.wikipedia.org/wiki/Benetton_Formula');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('bmw', 'BMW', 'de', 'http://en.wikipedia.org/wiki/BMW');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('bmw_sauber', 'BMW Sauber', 'de', 'http://en.wikipedia.org/wiki/BMW_Sauber');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('boro', 'Boro', 'nl', 'http://en.wikipedia.org/wiki/Boro_(Formula_One)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brabham', 'Brabham', 'gb', 'http://en.wikipedia.org/wiki/Brabham');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brabham-alfa_romeo', 'Brabham-Alfa Romeo', 'gb', 'http://en.wikipedia.org/wiki/Brabham');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brabham-brm', 'Brabham-BRM', 'gb', 'http://en.wikipedia.org/wiki/Brabham');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brabham-climax', 'Brabham-Climax', 'gb', 'http://en.wikipedia.org/wiki/Brabham');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brabham-ford', 'Brabham-Ford', 'gb', 'http://en.wikipedia.org/wiki/Brabham');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brabham-repco', 'Brabham-Repco', 'gb', 'http://en.wikipedia.org/wiki/Brabham');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brawn', 'Brawn', 'gb', 'http://en.wikipedia.org/wiki/Brawn_GP');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brm', 'BRM', 'gb', 'http://en.wikipedia.org/wiki/BRM');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brm-ford', 'BRM-Ford', 'gb', 'http://en.wikipedia.org/wiki/BRM');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('bromme', 'Bromme', 'us', 'http://en.wikipedia.org/wiki/Bromme');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('brp', 'BRP', 'gb', 'http://en.wikipedia.org/wiki/British_Racing_Partnership');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('bugatti', 'Bugatti', 'fr', 'http://en.wikipedia.org/wiki/Bugatti');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('caterham', 'Caterham', 'my', 'http://en.wikipedia.org/wiki/Caterham_F1');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('vhristensen', 'Christensen', 'us', 'http://en.wikipedia.org/wiki/Christensen_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cisitalia', 'Cisitalia', 'it', 'http://en.wikipedia.org/wiki/Cisitalia');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('coloni', 'Coloni', 'it', 'http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('connaught', 'Connaught', 'gb', 'http://en.wikipedia.org/wiki/Connaught_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('connew', 'Connew', 'gb', 'http://en.wikipedia.org/wiki/Connew');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper', 'Cooper', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-alfa_romeo', 'Cooper-Alfa Romeo', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-ats', 'Cooper-ATS', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-borgward', 'Cooper-Borgward', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-brm', 'Cooper-BRM', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-castellotti', 'Cooper-Castellotti', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-climax', 'Cooper-Climax', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-ferrari', 'Cooper-Ferrari', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-ford', 'Cooper-Ford', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-maserati', 'Cooper-Maserati', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('cooper-osca', 'Cooper-OSCA', 'gb', 'http://en.wikipedia.org/wiki/Cooper_Car_Company');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('dallara', 'Dallara', 'it', 'http://en.wikipedia.org/wiki/Dallara');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('tomaso', 'De Tomaso', 'it', 'http://en.wikipedia.org/wiki/De_Tomaso');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('de_tomaso-alfa_romeo', 'De Tomaso-Alfa Romeo', 'it', 'http://en.wikipedia.org/wiki/De_Tomaso');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('de_tomaso-ferrari', 'De Tomaso-Ferrari', 'it', 'http://en.wikipedia.org/wiki/De_Tomaso');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('de_tomaso-osca', 'De Tomaso-Osca', 'it', 'http://en.wikipedia.org/wiki/De_Tomaso');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('deidt', 'Deidt', 'us', 'http://en.wikipedia.org/wiki/Deidt');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('del_roy', 'Del Roy', 'us', 'http://en.wikipedia.org/wiki/Del_Roy');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('derrington', 'Derrington', 'gb', 'http://en.wikipedia.org/wiki/Derrington-Francis');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('dunn', 'Dunn', 'us', 'http://en.wikipedia.org/wiki/Dunn_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('eagle', 'Eagle', 'us', 'http://en.wikipedia.org/wiki/Anglo_American_Racers');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('eagle-climax', 'Eagle-Climax', 'us', 'http://en.wikipedia.org/wiki/Anglo_American_Racers');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('eagle-weslake', 'Eagle-Weslake', 'us', 'http://en.wikipedia.org/wiki/Anglo_American_Racers');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('elder', 'Elder', 'us', 'http://en.wikipedia.org/wiki/Elder_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('hill', 'Embassy Hill', 'gb', 'http://en.wikipedia.org/wiki/Hill_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('emeryson', 'Emeryson', 'gb', 'http://en.wikipedia.org/wiki/Emeryson');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('emw', 'EMW', 'dd', 'http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('enb', 'ENB', 'be', 'http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ensign', 'Ensign', 'gb', 'http://en.wikipedia.org/wiki/Ensign_%28racing_team%29');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('epperly', 'Epperly', 'us', 'http://en.wikipedia.org/wiki/Epperly');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('era', 'ERA', 'gb', 'http://en.wikipedia.org/wiki/English_Racing_Automobiles');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('eurobrun', 'Euro Brun', 'it', 'http://en.wikipedia.org/wiki/Euro_Brun');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ewing', 'Ewing', 'us', 'http://en.wikipedia.org/wiki/Ewing_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ferguson', 'Ferguson', 'gb', 'http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ferrari', 'Ferrari', 'it', 'http://en.wikipedia.org/wiki/Scuderia_Ferrari');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('fittipaldi', 'Fittipaldi', 'br', 'http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('fondmetal', 'Fondmetal', 'it', 'http://en.wikipedia.org/wiki/Fondmetal');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('footwork', 'Footwork', 'gb', 'http://en.wikipedia.org/wiki/Footwork_Arrows');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('force_india', 'Force India', 'in', 'http://en.wikipedia.org/wiki/Racing_Point_Force_India');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('forti', 'Forti', 'it', 'http://en.wikipedia.org/wiki/Forti');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('frazer_nash', 'Frazer Nash', 'gb', 'http://en.wikipedia.org/wiki/Frazer_Nash');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('fry', 'Fry', 'gb', 'http://en.wikipedia.org/wiki/Fry_(racing_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('gilby', 'Gilby', 'gb', 'http://en.wikipedia.org/wiki/Gilby');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('gordini', 'Gordini', 'fr', 'http://en.wikipedia.org/wiki/Gordini');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('haas', 'Haas F1 Team', 'us', 'http://en.wikipedia.org/wiki/Haas_F1_Team');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('hall', 'Hall', 'us', 'http://en.wikipedia.org/wiki/Hall_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('hesketh', 'Hesketh', 'gb', 'http://en.wikipedia.org/wiki/Hesketh_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('honda', 'Honda', 'jp', 'http://en.wikipedia.org/wiki/Honda_Racing_F1');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('hrt', 'HRT', 'es', 'http://en.wikipedia.org/wiki/Hispania_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('hwm', 'HWM', 'gb', 'http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('iso_marlboro', 'Iso Marlboro', 'gb', 'http://en.wikipedia.org/wiki/Iso_Marlboro');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('jaguar', 'Jaguar', 'gb', 'http://en.wikipedia.org/wiki/Jaguar_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('jbw', 'JBW', 'gb', 'http://en.wikipedia.org/wiki/JBW');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('jordan', 'Jordan', 'ie', 'http://en.wikipedia.org/wiki/Jordan_Grand_Prix');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('kauhsen', 'Kauhsen', 'de', 'http://en.wikipedia.org/wiki/Kauhsen');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('klenk', 'Klenk', 'de', 'http://en.wikipedia.org/wiki/Klenk');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('kojima', 'Kojima', 'jp', 'http://en.wikipedia.org/wiki/Kojima_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('kurtis_kraft', 'Kurtis Kraft', 'us', 'http://en.wikipedia.org/wiki/Kurtis_Kraft');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('kuzma', 'Kuzma', 'us', 'http://en.wikipedia.org/wiki/Kuzma_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lambo', 'Lambo', 'it', 'http://en.wikipedia.org/wiki/Modena_(racing_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lancia', 'Lancia', 'it', 'http://en.wikipedia.org/wiki/Lancia_in_Formula_One');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('langley', 'Langley', 'us', 'http://en.wikipedia.org/wiki/Langley_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('larrousse', 'Larrousse', 'fr', 'http://en.wikipedia.org/wiki/Larrousse');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lds', 'LDS', 'za', 'http://en.wikipedia.org/wiki/LDS_(automobile)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lds-alfa_romeo', 'LDS-Alfa Romeo', 'za', 'http://en.wikipedia.org/wiki/LDS_(automobile)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lds-climax', 'LDS-Climax', 'za', 'http://en.wikipedia.org/wiki/LDS_(automobile)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lec', 'LEC', 'gb', 'http://en.wikipedia.org/wiki/LEC_(Formula_One)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lesovsky', 'Lesovsky', 'us', 'http://en.wikipedia.org/wiki/Lesovsky');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('leyton', 'Leyton House', 'gb', 'http://en.wikipedia.org/wiki/Leyton_House');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('life', 'Life', 'it', 'http://en.wikipedia.org/wiki/Life_(Racing_Team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ligier', 'Ligier', 'fr', 'http://en.wikipedia.org/wiki/Ligier');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lola', 'Lola', 'gb', 'http://en.wikipedia.org/wiki/MasterCard_Lola');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus_racing', 'Lotus', 'my', 'http://en.wikipedia.org/wiki/Lotus_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus_f1', 'Lotus F1', 'gb', 'http://en.wikipedia.org/wiki/Lotus_F1');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus-borgward', 'Lotus-Borgward', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus-brm', 'Lotus-BRM', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus-climax', 'Lotus-Climax', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus-ford', 'Lotus-Ford', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus-maserati', 'Lotus-Maserati', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lotus-pw', 'Lotus-Pratt &amp: Whitney', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lyncar', 'Lyncar', 'gb', 'http://en.wikipedia.org/wiki/Lyncar');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('maki', 'Maki', 'jp', 'http://en.wikipedia.org/wiki/Maki_(cars)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('manor', 'Manor Marussia', 'gb', 'http://en.wikipedia.org/wiki/Manor_Motorsport');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('march', 'March', 'gb', 'http://en.wikipedia.org/wiki/March_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('march-alfa_romeo', 'March-Alfa Romeo', 'gb', 'http://en.wikipedia.org/wiki/March_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('march-ford', 'March-Ford', 'gb', 'http://en.wikipedia.org/wiki/March_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('marchese', 'Marchese', 'us', 'http://en.wikipedia.org/wiki/Marchese_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('martini', 'Martini', 'fr', 'http://en.wikipedia.org/wiki/Martini_(cars)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('marussia', 'Marussia', 'ru', 'http://en.wikipedia.org/wiki/Marussia_F1');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('maserati', 'Maserati', 'it', 'http://en.wikipedia.org/wiki/Maserati');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('matra', 'Matra', 'fr', 'http://en.wikipedia.org/wiki/Matra');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('matra-ford', 'Matra-Ford', 'fr', 'http://en.wikipedia.org/wiki/Matra');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mbm', 'MBM', 'ch', 'http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mcguire', 'McGuire', 'au', 'http://en.wikipedia.org/wiki/McGuire_(Formula_One)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mclaren', 'McLaren', 'gb', 'http://en.wikipedia.org/wiki/McLaren');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mclaren-alfa_romeo', 'McLaren-Alfa Romeo', 'gb', 'http://en.wikipedia.org/wiki/McLaren_(racing)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mclaren-brm', 'McLaren-BRM', 'gb', 'http://en.wikipedia.org/wiki/McLaren_(racing)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mclaren-ford', 'McLaren-Ford', 'gb', 'http://en.wikipedia.org/wiki/Team_McLaren');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mclaren-seren', 'McLaren-Serenissima', 'gb', 'http://en.wikipedia.org/wiki/Team_McLaren');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mercedes', 'Mercedes', 'de', 'http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('merzario', 'Merzario', 'it', 'http://en.wikipedia.org/wiki/Merzario');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('meskowski', 'Meskowski', 'us', 'http://en.wikipedia.org/wiki/Meskowski');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('mf1', 'MF1', 'ru', 'http://en.wikipedia.org/wiki/Midland_F1_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('milano', 'Milano', 'it', 'http://en.wikipedia.org/wiki/Scuderia_Milano');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('minardi', 'Minardi', 'it', 'http://en.wikipedia.org/wiki/Minardi');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('moore', 'Moore', 'us', 'http://en.wikipedia.org/wiki/Moore_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('nichels', 'Nichels', 'us', 'http://en.wikipedia.org/wiki/Nichels');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('olson', 'Olson', 'us', 'http://en.wikipedia.org/wiki/Olson_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('onyx', 'Onyx', 'gb', 'http://en.wikipedia.org/wiki/Onyx_(racing_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('osca', 'OSCA', 'it', 'http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('osella', 'Osella', 'it', 'http://en.wikipedia.org/wiki/Osella');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('pacific', 'Pacific', 'gb', 'http://en.wikipedia.org/wiki/Pacific_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('pankratz', 'Pankratz', 'us', 'http://en.wikipedia.org/wiki/Pankratz');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('parnelli', 'Parnelli', 'us', 'http://en.wikipedia.org/wiki/Parnelli');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('pawl', 'Pawl', 'us', 'http://en.wikipedia.org/wiki/Pawl_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('penske', 'Penske', 'us', 'http://en.wikipedia.org/wiki/Penske_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('phillips', 'Phillips', 'us', 'http://en.wikipedia.org/wiki/Phillips_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('politoys', 'Politoys', 'gb', 'http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('porsche', 'Porsche', 'de', 'http://en.wikipedia.org/wiki/Porsche_in_Formula_One');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('prost', 'Prost', 'fr', 'http://en.wikipedia.org/wiki/Prost_Grand_Prix');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('protos', 'Protos', 'gb', 'http://en.wikipedia.org/wiki/Protos_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('racing_point', 'Racing Point', 'gb', 'http://en.wikipedia.org/wiki/Racing_Point_F1_Team');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('rae', 'Rae', 'us', 'http://en.wikipedia.org/wiki/Rae_(motorsport)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('ram', 'RAM', 'gb', 'http://en.wikipedia.org/wiki/RAM_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('re', 'RE', 'rh', 'http://en.wikipedia.org/wiki/RE_%28automobile%29');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('rebaque', 'Rebaque', 'mx', 'http://en.wikipedia.org/wiki/Rebaque');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('red_bull', 'Red Bull', 'at', 'http://en.wikipedia.org/wiki/Red_Bull_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('renault', 'Renault', 'fr', 'http://en.wikipedia.org/wiki/Renault_in_Formula_One');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('rial', 'Rial', 'de', 'http://en.wikipedia.org/wiki/Rial_%28racing_team%29');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('sauber', 'Sauber', 'ch', 'http://en.wikipedia.org/wiki/Sauber');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('scarab', 'Scarab', 'us', 'http://en.wikipedia.org/wiki/Scarab_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('schroeder', 'Schroeder', 'us', 'http://en.wikipedia.org/wiki/Schroeder_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('scirocco', 'Scirocco', 'gb', 'http://en.wikipedia.org/wiki/Scirocco-Powell');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('shadow', 'Shadow', 'gb', 'http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('shadow-ford', 'Shadow-Ford', 'gb', 'http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('shadow-matra', 'Shadow-Matra', 'gb', 'http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('shannon', 'Shannon', 'gb', 'http://en.wikipedia.org/wiki/Shannon_(Formula_One)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('sherman', 'Sherman', 'us', 'http://en.wikipedia.org/wiki/Sherman_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('simca', 'Simca', 'fr', 'http://en.wikipedia.org/wiki/Simca');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('simtek', 'Simtek', 'gb', 'http://en.wikipedia.org/wiki/Simtek');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('snowberger', 'Snowberger', 'us', 'http://en.wikipedia.org/wiki/Snowberger');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('spirit', 'Spirit', 'gb', 'http://en.wikipedia.org/wiki/Spirit_(racing_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('spyker', 'Spyker', 'nl', 'http://en.wikipedia.org/wiki/Spyker_F1');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('spyker_mf1', 'Spyker MF1', 'nl', 'http://en.wikipedia.org/wiki/Midland_F1_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('stebro', 'Stebro', 'ca', 'http://en.wikipedia.org/wiki/Stebro');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('stevens', 'Stevens', 'us', 'http://en.wikipedia.org/wiki/Stevens_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('stewart', 'Stewart', 'gb', 'http://en.wikipedia.org/wiki/Stewart_Grand_Prix');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('super_aguri', 'Super Aguri', 'jp', 'http://en.wikipedia.org/wiki/Super_Aguri_F1');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('surtees', 'Surtees', 'gb', 'http://en.wikipedia.org/wiki/Surtees');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('sutton', 'Sutton', 'us', 'http://en.wikipedia.org/wiki/Sutton_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('lago', 'Talbot-Lago', 'fr', 'http://en.wikipedia.org/wiki/Talbot-Lago');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('team_lotus', 'Team Lotus', 'gb', 'http://en.wikipedia.org/wiki/Team_Lotus');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('tec-mec', 'Tec-Mec', 'it', 'http://en.wikipedia.org/wiki/Tec-Mec');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('tecno', 'Tecno', 'it', 'http://en.wikipedia.org/wiki/Tecno');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('theodore', 'Theodore', 'hk', 'http://en.wikipedia.org/wiki/Theodore_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('token', 'Token', 'gb', 'http://en.wikipedia.org/wiki/Token_(Racing_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('toleman', 'Toleman', 'gb', 'http://en.wikipedia.org/wiki/Toleman');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('toro_rosso', 'Toro Rosso', 'it', 'http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('toyota', 'Toyota', 'jp', 'http://en.wikipedia.org/wiki/Toyota_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('trevis', 'Trevis', 'us', 'http://en.wikipedia.org/wiki/Trevis');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('trojan', 'Trojan', 'gb', 'http://en.wikipedia.org/wiki/Trojan_(Racing_team)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('turner', 'Turner', 'us', 'http://en.wikipedia.org/wiki/Turner_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('tyrrell', 'Tyrrell', 'gb', 'http://en.wikipedia.org/wiki/Tyrrell_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('vanwall', 'Vanwall', 'gb', 'http://en.wikipedia.org/wiki/Vanwall');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('veritas', 'Veritas', 'de', 'http://en.wikipedia.org/wiki/Veritas_(constructor)');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('virgin', 'Virgin', 'gb', 'http://en.wikipedia.org/wiki/Virgin_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('watson', 'Watson', 'us', 'http://en.wikipedia.org/wiki/A.J._Watson');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('wetteroth', 'Wetteroth', 'us', 'http://en.wikipedia.org/wiki/Wetteroth');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('williams', 'Williams', 'gb', 'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('wolf', 'Wolf', 'ca', 'http://en.wikipedia.org/wiki/Walter_Wolf_Racing');
insert into constructors (constructor_identifier, name, country_code, wikipedia_page) values ('zakspeed', 'Zakspeed', 'de', 'http://en.wikipedia.org/wiki/Zakspeed');