package common.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;

import static java.util.Collections.emptyList;

@AllArgsConstructor
@Getter
public enum Country{
    AFGHANISTAN("af", "AFG", List.of("afghanistan"), emptyList()),
    ALBANIA("al", "ALB", List.of("albania"), emptyList()),
    ALGERIA("dz", "ALG", List.of("algeria"), emptyList()),
    AMERICAN_SAMOA("as", "ASA", List.of("american_samoa"), emptyList()),
    ANDORRA("ad", "AND", List.of("andorra"), emptyList()),
    ANGOLA("ao", "ANG", List.of("angola"), emptyList()),
    ANGUILLA("ai", "AIA", List.of("anguilla"), emptyList()),
    ANTARCTICA("aq", null, List.of("antarctica"), emptyList()),
    ANTIGUA_AND_BARBUDA("ag", "ANT", List.of("antigua_and_barbuda"), emptyList()),
    ARGENTINA("ar", "ARG", List.of("argentina"), List.of("argentine", "argentine-italian")),
    ARMENIA("am", "ARM", List.of("armenia"), emptyList()),
    ARUBA("aw", "ARU", List.of("aruba"), emptyList()),
    AUSTRALIA("au", "AUS", List.of("australia"), List.of("australian")),
    AUSTRIA("at", "AUT", List.of("austria"), List.of("austrian")),
    AZERBAIJAN("az", "AZE", List.of("azerbaijan"), emptyList()),
    BAHAMAS("bs", "BAH", List.of("bahamas"), emptyList()),
    BAHRAIN("bh", "BRN", List.of("bahrain"), emptyList()),
    BANGLADESH("bd", "BAN", List.of("bangladesh"), emptyList()),
    BARBADOS("bb", "BAR", List.of("barbados"), emptyList()),
    BELARUS("by", "BLR", List.of("belarus"), emptyList()),
    BELGIUM("be", "BEL", List.of("belgium"), List.of("belgium", "belgian")),
    BELIZE("bz", "BIZ", List.of("belize"), emptyList()),
    BENIN("bj", "BEN", List.of("benin"), emptyList()),
    BERMUDA("bm", "BER", List.of("bermuda"), emptyList()),
    BHUTAN("bt", "BHU", List.of("bhutan"), emptyList()),
    BOLIVIA("bo", "BOL", List.of("bolivia"), emptyList()),
    BOSNIA_AND_HERZEGOVINA("ba", "BIH", List.of("bosnia_and_herzegovina"), emptyList()),
    BOTSWANA("bw", "BOT", List.of("botswana"), emptyList()),
    BRAZIL("br", "BRA", List.of("brazil"), List.of("brazilian")),
    BRITISH_INDIAN_OCEAN_TERRITORY("io", null, List.of("british_indian_ocean_territory"), emptyList()),
    BRITISH_VIRGIN_ISLANDS("vg", "IVB", List.of("british_virgin_islands"), emptyList()),
    BRUNEI("bn", "BRU", List.of("brunei"), emptyList()),
    BULGARIA("bg", "BUL", List.of("bulgaria"), emptyList()),
    BURKINA_FASO("bf", "BUR", List.of("burkina_faso"), emptyList()),
    BURUNDI("bi", "BDI", List.of("burundi"), emptyList()),
    CAMBODIA("kh", "CAM", List.of("cambodia"), emptyList()),
    CAMEROON("cm", "CMR", List.of("cameroon"), emptyList()),
    CANADA("ca", "CAN", List.of("canada"), List.of("canadian")),
    CAPE_VERDE("cv", "CPV", List.of("cape_verde"), emptyList()),
    CAYMAN_ISLANDS("ky", "CAY", List.of("cayman_islands"), emptyList()),
    CENTRAL_AFRICAN_REPUBLIC("cf", "CAF", List.of("central_african_republic"), emptyList()),
    CHAD("td", "CHA", List.of("chad"), emptyList()),
    CHILE("cl", "CHI", List.of("chile"), List.of("chilean")),
    CHINA("cn", "CHN", List.of("china"), List.of("chinese")),
    CHRISTMAS_ISLAND("cx", null, List.of("christmas_island"), emptyList()),
    COCOS_ISLANDS("cc", null, List.of("cocos_islands"), emptyList()),
    COLOMBIA("co", "COL", List.of("colombia"), List.of("colombian")),
    COMOROS("km", "COM", List.of("comoros"), emptyList()),
    COOK_ISLANDS("ck", "COK", List.of("cook_islands"), emptyList()),
    COSTA_RICA("cr", "CRC", List.of("costa_rica"), emptyList()),
    CROATIA("hr", "CRO", List.of("croatia"), emptyList()),
    CUBA("cu", "CUB", List.of("cuba"), emptyList()),
    CURACAO("cw", null, List.of("curacao"), emptyList()),
    CYPRUS("cy", "CYP", List.of("cyprus"), emptyList()),
    CZECH_REPUBLIC("cz", "CZE", List.of("czech_republic"), List.of("czech")),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("cd", "COD", List.of("democratic_republic_of_the_congo"), emptyList()),
    DENMARK("dk", "DEN", List.of("denmark"), List.of("danish")),
    DJIBOUTI("dj", "DJI", List.of("djibouti"), emptyList()),
    DOMINICA("dm", "DMA", List.of("dominica"), emptyList()),
    DOMINICAN_REPUBLIC("do", "DOM", List.of("dominican_republic"), emptyList()),
    EAST_GERMANY("dd", "GDR", List.of("east_germany"), List.of("east german")),
    EAST_TIMOR("tl", "TLS", List.of("east_timor"), emptyList()),
    ECUADOR("ec", "ECU", List.of("ecuador"), emptyList()),
    EGYPT("eg", "EGY", List.of("egypt"), emptyList()),
    EL_SALVADOR("sv", "ESA", List.of("el_salvador"), emptyList()),
    EQUATORIAL_GUINEA("gq", "GEQ", List.of("equatorial_guinea"), emptyList()),
    ERITREA("er", "ERI", List.of("eritrea"), emptyList()),
    ESTONIA("ee", "EST", List.of("estonia"), emptyList()),
    ETHIOPIA("et", "ETH", List.of("ethiopia"), emptyList()),
    FALKLAND_ISLANDS("fk", null, List.of("falkland_islands"), emptyList()),
    FAROE_ISLANDS("fo", "FRO", List.of("faroe_islands"), emptyList()),
    FIJI("fj", "FIJ", List.of("fiji"), emptyList()),
    FINLAND("fi", "FIN", List.of("finland"), List.of("finnish")),
    FRANCE("fr", "FRA", List.of("france"),  List.of("french")),
    FRENCH_POLYNESIA("pf", "FRA", List.of("french_polynesia"), emptyList()),
    GABON("ga", "GAB", List.of("gabon"), emptyList()),
    GAMBIA("gm", "GAM", List.of("gambia"), emptyList()),
    GEORGIA("ge", "GEO", List.of("georgia"), emptyList()),
    GERMANY("de", "GER", List.of("germany"),  List.of("german")),
    GHANA("gh", "GHA", List.of("ghana"), emptyList()),
    GIBRALTAR("gi", null, List.of("gibraltar"), emptyList()),
    GREECE("gr", "GRE", List.of("greece"), emptyList()),
    GREENLAND("gl", null, List.of("greenland"), emptyList()),
    GRENADA("gd", "GRN", List.of("grenada"), emptyList()),
    GUAM("gu", "GUM", List.of("guam"), emptyList()),
    GUATEMALA("gt", "GUA", List.of("guatemala"), emptyList()),
    GUERNSEY("gg", null, List.of("guernsey"), emptyList()),
    GUINEA("gn", "GUI", List.of("guinea"), emptyList()),
    GUINEA_BISSAU("gw", "GBS", List.of("guinea_bissau"), emptyList()),
    GUYANA("gy", "GUY", List.of("guyana"), emptyList()),
    HAITI("ht", "HAI", List.of("haiti"), emptyList()),
    HONDURAS("hn", "HON", List.of("honduras"), emptyList()),
    HONG_KONG("hk", "HKG", List.of("hong_kong"), List.of("hong kong")),
    HUNGARY("hu", "HUN", List.of("hungary"), List.of("hungarian")),
    ICELAND("is", "ISL", List.of("iceland"), emptyList()),
    INDIA("in", "IND", List.of("india"), List.of("indian")),
    INDONESIA("id", "INA", List.of("indonesia"), List.of("indonesian")),
    IRAN("ir", "IRI", List.of("iran"), emptyList()),
    IRAQ("iq", "IRQ", List.of("iraq"), emptyList()),
    IRELAND("ie", "IRL", List.of("ireland"), List.of("irish")),
    ISLE_OF_MAN("im", null, List.of("isle_of_man"), emptyList()),
    ISRAEL("il", "ISR", List.of("israel"), emptyList()),
    ITALY("it", "ITA", List.of("italy"),  List.of("italian")),
    IVORY_COAST("ci", "CIV", List.of("ivory_coast"), emptyList()),
    JAMAICA("jm", "JAM", List.of("jamaica"), emptyList()),
    JAPAN("jp", "JPN", List.of("japan"), List.of("japanese")),
    JERSEY("je", null, List.of("jersey"), emptyList()),
    JORDAN("jo", "JOR", List.of("jordan"), emptyList()),
    KAZAKHSTAN("kz", "KAZ", List.of("kazakhstan"), emptyList()),
    KENYA("ke", "KEN", List.of("kenya"), emptyList()),
    KIRIBATI("ki", "KIR", List.of("kiribati"), emptyList()),
    KOSOVO("xk", "KOS", List.of("kosovo"), emptyList()),
    KUWAIT("kw", "KUW", List.of("kuwait"), emptyList()),
    KYRGYZSTAN("kg", "KGZ", List.of("kyrgyzstan"), emptyList()),
    LAOS("la", "LAO", List.of("laos"), emptyList()),
    LATVIA("lv", "LAT", List.of("latvia"), emptyList()),
    LEBANON("lb", "LBN", List.of("lebanon"), emptyList()),
    LESOTHO("ls", "LES", List.of("lesotho"), emptyList()),
    LIBERIA("lr", "LBR", List.of("liberia"), emptyList()),
    LIBYA("ly", "LBA", List.of("libya"), emptyList()),
    LIECHTENSTEIN("li", "LIE", List.of("liechtenstein"), List.of("liechtensteiner")),
    LITHUANIA("lt", "LTU", List.of("lithuania"), emptyList()),
    LUXEMBOURG("lu", "LUX", List.of("luxembourg"), emptyList()),
    MACAU("mo", "MAC", List.of("macau"), emptyList()),
    MACEDONIA("mk", "MKD", List.of("macedonia"), emptyList()),
    MADAGASCAR("mg", "MAD", List.of("madagascar"), emptyList()),
    MALAWI("mw", "MAW", List.of("malawi"), emptyList()),
    MALAYSIA("my", "MAS", List.of("malaysia"),  List.of("malaysian")),
    MALDIVES("mv", "MDV", List.of("maldives"), emptyList()),
    MALI("ml", "MLI", List.of("mali"), emptyList()),
    MALTA("mt", "MLT", List.of("malta"), emptyList()),
    MARSHALL_ISLANDS("mh", "MHL", List.of("marshall_islands"), emptyList()),
    MAURITANIA("mr", "MTN", List.of("mauritania"), emptyList()),
    MAURITIUS("mu", "MRI", List.of("mauritius"), emptyList()),
    MAYOTTE("yt", null, List.of("mayotte"), emptyList()),
    MEXICO("mx", "MEX", List.of("mexico"), List.of("mexican")),
    MICRONESIA("fm", "FSM", List.of("micronesia"), emptyList()),
    MOLDOVA("md", "MDA", List.of("moldova"), emptyList()),
    MONACO("mc", "MON", List.of("monaco"), List.of("monegasque")),
    MONGOLIA("mn", "MGL", List.of("mongolia"), emptyList()),
    MONTENEGRO("me", "MNE", List.of("montenegro"), emptyList()),
    MONTSERRAT("ms", null, List.of("montserrat"), emptyList()),
    MOROCCO("ma", "MAR", List.of("morocco"), emptyList()),
    MOZAMBIQUE("mz", "MOZ", List.of("mozambique"), emptyList()),
    MYANMAR("mm", "MYA", List.of("myanmar"), emptyList()),
    NAMIBIA("na", "NAM", List.of("namibia"), emptyList()),
    NAURU("nr", "NRU", List.of("nauru"), emptyList()),
    NEPAL("np", "NEP", List.of("nepal"), emptyList()),
    NETHERLANDS("nl", "NED", List.of("netherlands"),  List.of("dutch")),
    NETHERLANDS_ANTILLES("an", "AHO", List.of("netherlands_antilles"), emptyList()),
    NEW_CALEDONIA("nc", null, List.of("new_caledonia"), emptyList()),
    NEW_ZEALAND("nz", "NZL", List.of("new_zealand"),  List.of("new zealand", "new zealander")),
    NICARAGUA("ni", "NCA", List.of("nicaragua"), emptyList()),
    NIGER("ne", "NIG", List.of("niger"), emptyList()),
    NIGERIA("ng", "NGR", List.of("nigeria"), emptyList()),
    NIUE("nu", null, List.of("niue"), emptyList()),
    NORTH_KOREA("kp", "PRK", List.of("north_korea"), emptyList()),
    NORTHERN_MARIANA_ISLANDS("mp", null, List.of("northern_mariana_islands"), emptyList()),
    NORWAY("no", "NOR", List.of("norway"), emptyList()),
    OMAN("om", "OMA", List.of("oman"), emptyList()),
    PAKISTAN("pk", "PAK", List.of("pakistan"), emptyList()),
    PALAU("pw", "PLW", List.of("palau"), emptyList()),
    PALESTINE("ps", "PLE", List.of("palestine"), emptyList()),
    PANAMA("pa", "PAN", List.of("panama"), emptyList()),
    PAPUA_NEW_GUINEA("pg", "PNG", List.of("papua_new_guinea"), emptyList()),
    PARAGUAY("py", "PAR", List.of("paraguay"), emptyList()),
    PERU("pe", "PER", List.of("peru"), emptyList()),
    PHILIPPINES("ph", "PHI", List.of("philippines"), emptyList()),
    PITCAIRN("pn", null, List.of("pitcairn"), emptyList()),
    POLAND("pl", "POL", List.of("poland"), List.of("polish")),
    PORTUGAL("pt", "POR", List.of("portugal"), List.of("portuguese")),
    PUERTO_RICO("pr", "PUR", List.of("puerto_rico"), emptyList()),
    QATAR("qa", "QAT", List.of("qatar"), emptyList()),
    REPUBLIC_OF_THE_CONGO("cg", "CGO", List.of("republic_of_the_congo"), emptyList()),
    REUNION("re", null, List.of("reunion"), emptyList()),
    RHODESIA("rh", "RHO", List.of("rhodesia"), List.of("rhodesian")),
    ROMANIA("ro", "ROU", List.of("romania"), emptyList()),
    RUSSIA("ru", "RUS", List.of("russia"), List.of("russian")),
    RWANDA("rw", "RWA", List.of("rwanda"), emptyList()),
    SAINT_BARTHELEMY("bl", null, List.of("saint_barthelemy"), emptyList()),
    SAINT_HELENA("sh", null, List.of("saint_helena"), emptyList()),
    SAINT_KITTS_AND_NEVIS("kn", "SKN", List.of("saint_kitts_and_nevis"), emptyList()),
    SAINT_LUCIA("lc", "LCA", List.of("saint_lucia"), emptyList()),
    SAINT_MARTIN("mf", null, List.of("saint_martin"), emptyList()),
    SAINT_PIERRE_AND_MIQUELON("pm", null, List.of("saint_pierre_and_miquelon"), emptyList()),
    SAINT_VINCENT_AND_THE_GRENADINES("vc", "VIN", List.of("saint_vincent_and_the_grenadines"), emptyList()),
    SAMOA("ws", "SAM", List.of("samoa"), emptyList()),
    SAN_MARINO("sm", "SMR", List.of("san_marino"), emptyList()),
    SAO_TOME_AND_PRINCIPE("st", "STP", List.of("sao_tome_and_principe"), emptyList()),
    SAUDI_ARABIA("sa", "KSA", List.of("saudi arabia"), emptyList()),
    SENEGAL("sn", "SEN", List.of("senegal"), emptyList()),
    SERBIA("rs", "SRB", List.of("serbia"), emptyList()),
    SEYCHELLES("sc", "SEY", List.of("seychelles"), emptyList()),
    SIERRA_LEONE("sl", "SLE", List.of("sierra_leone"), emptyList()),
    SINGAPORE("sg", "SGP", List.of("singapore"), emptyList()),
    SINT_MAARTEN("sx", null, List.of("sint_maarten"), emptyList()),
    SLOVAKIA("sk", "SVK", List.of("slovakia"), emptyList()),
    SLOVENIA("si", "SLO", List.of("slovenia"), emptyList()),
    SOLOMON_ISLANDS("sb", "SOL", List.of("solomon_islands"), emptyList()),
    SOMALIA("so", "SOM", List.of("somalia"), emptyList()),
    SOUTH_AFRICA("za", "RSA", List.of("south africa"), List.of("south african")),
    SOUTH_KOREA("kr", "KOR", List.of("korea"), emptyList()),
    SOUTH_SUDAN("ss", "SSD", List.of("south_sudan"), emptyList()),
    SPAIN("es", "ESP", List.of("spain"), List.of("spanish")),
    SRI_LANKA("lk", "SRI", List.of("sri_lanka"), emptyList()),
    SUDAN("sd", "SUD", List.of("sudan"), emptyList()),
    SURINAME("sr", "SUR", List.of("suriname"), emptyList()),
    SVALBARD_AND_JAN_MAYEN("sj", null, List.of("svalbard_and_jan_mayen"), emptyList()),
    SWAZILAND("sz", "SWZ", List.of("swaziland"), emptyList()),
    SWEDEN("se", "SWE", List.of("sweden"), List.of("swedish")),
    SWITZERLAND("ch", "SUI", List.of("switzerland"),  List.of("swiss")),
    SYRIA("sy", "SYR", List.of("syria"), emptyList()),
    TAIWAN("tw", "TPE", List.of("taiwan"), emptyList()),
    TAJIKISTAN("tj", "TJK", List.of("tajikistan"), emptyList()),
    TANZANIA("tz", "TAN", List.of("tanzania"), emptyList()),
    THAILAND("th", "THA", List.of("thailand"), List.of("thai")),
    TOGO("tg", "TOG", List.of("togo"), emptyList()),
    TOKELAU("tk", null, List.of("tokelau"), emptyList()),
    TONGA("to", "TGA", List.of("tonga"), emptyList()),
    TRINIDAD_AND_TOBAGO("tt", "TTO", List.of("trinidad_and_tobago"), emptyList()),
    TUNISIA("tn", "TUN", List.of("tunisia"), emptyList()),
    TURKEY("tr", "TUR", List.of("turkey"), emptyList()),
    TURKMENISTAN("tm", "TKM", List.of("turkmenistan"), emptyList()),
    TURKS_AND_CAICOS_ISLANDS("tc", null, List.of("turks_and_caicos_islands"), emptyList()),
    TUVALU("tv", "TUV", List.of("tuvalu"), emptyList()),
    US_VIRGIN_ISLANDS("vi", "ISV", List.of("us_virgin_islands"), emptyList()),
    UGANDA("ug", "UGA", List.of("uganda"), emptyList()),
    UKRAINE("ua", "UKR", List.of("ukraine"), emptyList()),
    UNITED_ARAB_EMIRATES("ae", "UAE", List.of("uae"), emptyList()),
    UNITED_KINGDOM("gb", "GBR", List.of("uk"), List.of("british")),
    UNITED_STATES("us", "USA", List.of("usa", "united states"), List.of("american", "american-italian")),
    URUGUAY("uy", "URU", List.of("uruguay"), List.of("uruguayan")),
    UZBEKISTAN("uz", "UZB", List.of("uzbekistan"), emptyList()),
    VANUATU("vu", "VAN", List.of("vanuatu"), emptyList()),
    VATICAN("va", null, List.of("vatican"), emptyList()),
    VENEZUELA("ve", "VEN", List.of("venezuela"), List.of("venezuelan")),
    VIETNAM("vn", "VIE", List.of("vietnam"), emptyList()),
    WALLIS_AND_FUTUNA("wf", null, List.of("wallis_and_futuna"), emptyList()),
    WESTERN_SAHARA("eh", null, List.of("western_sahara"), emptyList()),
    YEMEN("ye", "YEM", List.of("yemen"), emptyList()),
    ZAMBIA("zm", "ZAM", List.of("zambia"), emptyList()),
    ZIMBABWE("zw", "ZIM", List.of("zimbabwe"), emptyList());

    private final String mCode;
    private final String mIOCCode;
    private final List<String> mNames;
    private final List<String> mNationalityKeywords;

    public static Country fromCountryCode(final String countryCode) {
        return Arrays.stream(values())
            .filter(country -> countryCode != null && country.mCode.equals(countryCode.toLowerCase()))
            .findFirst()
            .orElseThrow(() -> new IllegalArgumentException(String.format("Unable to parse the countryCode: %s to a valid country", countryCode)));
    }

    public static Country fromName(final String name) {
        return Arrays.stream(values())
            .filter(country -> name != null && country.mNames.contains(name.toLowerCase()))
            .findFirst()
            .orElseThrow(() -> new IllegalArgumentException(String.format("Unable to parse the name: %s to a valid country", name)));
    }

    public static Country fromNationality(final String nationality) {
         return Arrays.stream(values())
             .filter(country -> nationality != null && country.mNationalityKeywords.contains(nationality.toLowerCase()))
             .findFirst()
             .orElseThrow(() -> new IllegalArgumentException(String.format("Unable to parse the nationality: %s to a valid country", nationality)));
    }
}
